# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65b2a1fdab824a653d88d71e11a8ed8773355abc797d38ddaecd3ccafbea1510e5080275a54e6c733d4f96289921ed65fbafe30c9b6be5ffc59e5b673a7ef5d

test:
  secret_key_base: 81e1006741a24b9dcb895610f68c15c2ebd4323e6c9e59e2b13a7ee6eae05fc2ee1ba884eaf94cc4788359ab0558b65c607a81dcaff6ac8b5bb769b3f6409610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
